name: Build Manjaro XFCE ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Manjaro XFCE ISO
        uses: docker://talesam/community-build:1.3
        with:
          entrypoint: /bin/bash
        run: |
          # Atualize o sistema e instale as ferramentas necessárias
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git manjaro-tools

          # Execute a ferramenta buildiso
          # Substitua <config-file> pelo caminho para o arquivo de configuração do buildiso
          buildiso -v -c <config-file>

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3
        with:
          name: manjaro-xfce-iso
          path: /workspace/*.iso
