name: Build Manjaro XFCE ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display the current user in host
        run: |
          echo "#########################################"
          echo "Current host is: $(hostname)"
          echo "Current user is: $(whoami)"
          echo "Current user ID is: $(id -u)"
          echo "Current user details:"
          echo "#########################################"
          id
          df -hT

      - name: Print message and conditionally exit
        run: |
          CONDITION_MET=true
          if [ "$CONDITION_MET" = true ]; then
            echo "Condition met, continuing..."
          else
            echo "Condition not met, exiting..."
            exit 1  # Exiting with status code 1 will fail the job
          fi

      - name: Set up volume directory
        run: |
          #mkdir -p /home/runner/work/${{ github.repository }}/volume_data
          #mkdir -p /home/runner/work/${{ github.repository }}/volume_data_iso
          sudo mkdir -p /mnt/var_lib_manjaro_tools_buildiso
          sudo mkdir -p /mnt/var_cache_manjaro_tools

      - name: Setup TMATE Session
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: true
          detached: true

      - name: Print TMATE Session URL
        run: |
          echo "Access tmate session at: ${{ steps.tmate.outputs.tmate_web_url }}"

      - name: Build Manjaro XFCE ISO
        run: |
          docker run --rm --privileged \
            -v /mnt/var_lib_manjaro_tools_buildiso:/var/lib/manjaro-tools/buildiso \
            -v /mnt/var_cache_manjaro_tools:/var/cache/manjaro-tools \
            talesam/community-build:1.3 /bin/bash -c "
              # Atualize o sistema e instale as ferramentas necessárias
              pacman -Syu --noconfirm
              pacman -S --noconfirm base-devel git manjaro-tools manjaro-tools-iso

              # Remova qualquer instância existente do diretório iso-profiles e clone o repositório
              rm -rf /usr/share/manjaro-tools/iso-profiles
              git clone https://github.com/chililinux/iso-profiles.git /usr/share/manjaro-tools/iso-profiles

              # Verifique se o repositório foi clonado corretamente
              ls -l /usr/share/manjaro-tools/iso-profiles

              # Navegue para o diretório de perfis e verifique os perfis disponíveis
              cd /usr/share/manjaro-tools/iso-profiles
              ls -l

              # Execute a ferramenta buildiso com o perfil xfce
              buildiso -v -c /workspace/xfce
            "

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3
        with:
          name: manjaro-xfce-iso
          path: /workspace/*.iso
