name: Build Manjaro XFCE ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Manjaro XFCE ISO
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace talesam/community-build:1.3 /bin/bash -c "
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git manjaro-tools


            # Navegue até o diretório de perfis
            cd /usr/share/manjaro-tools/iso-profiles/manjaro

            # Verifique os perfis disponíveis
            ls -l

            # Execute a ferramenta buildiso com o perfil xfce
            buildiso -v -c /workspace/xfce
          "

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3
        with:
          name: manjaro-xfce-iso
          path: /workspace/*.iso
